- name: SETUP | Add epel release
  yum:
    name: epel-release
    state: latest

- name: SETUP | Yum install foreman_packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ foreman_packages }}"

- name: SETUP | Setup ansible.cfg
  template:
    src: ansible.cfg.jinja2
    dest: "{{ foreman_ansible_cfg_location }}"

- name: SETUP | Set permanent FOREMAN system variables
  lineinfile:
    path: "/etc/environment"
    line: "export {{item.var}}={{ item.value }}"
    regexp: "^export {{ item.var }}"
    state: present
    insertafter: EOF
  with_items: "{{ foreman_system_variables }}"