- name: SETUP | Add epel release
    yum:
      name: epel-release
      state: latest

- name: SETUP | Yum update packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ foreman_packages }}"

- name: SETUP | Setup ansible.cfg
  template:
    src: ansible.cfg.jinja2
    dest: "{{ foreman_ansible_cfg_location }}"